# Generated by Django 4.2.1 on 2023-05-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_city_fare_movie_screen_seatingclass_theater_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True),
        ),
    ]
