# Generated by Django 4.2.1 on 2023-05-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_show_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshowmapper',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True),
        ),
    ]
