# Generated by Django 4.2.1 on 2023-05-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_screenshowmapper_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fare',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True),
        ),
    ]
